services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME:-tharun}/resume-api:latest
    container_name: resume_api
    env_file:
      - .env
    environment:
      - APP_ENV=prod
      # Overrides or additional vars if needed
    volumes:
      - ./app:/app
      - ./app/_data:/app/_data
    ports:
      - "8000:8000"
    depends_on:
      - db

  ui:
    build: ./frontend
    image: ${DOCKER_USERNAME:-tharun}/resume-ui:latest
    container_name: resume_ui
    ports:
      - "5173:80"
    depends_on:
      - api

  db:
    image: postgres:16-alpine
    container_name: resume_db
    environment:
      - POSTGRES_USER=resume
      - POSTGRES_PASSWORD=resume
      - POSTGRES_DB=resumeai
    volumes:
      - pg:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg:
